/*
 * Festival PWA Standalone Service Worker — hardened offline caching.
 *
 * Strategy:
 *   - App shell / static assets  → Cache-First
 *   - Manifest + page JSON data  → Stale-While-Revalidate
 *   - Cross-origin assets        → Cache-First only for CORS/basic responses
 */

const CACHE_VERSION = '1786434353';
const APP_NAME = 'bucht-standalone';
const CACHE_NAME = `${APP_NAME}-v${CACHE_VERSION}`;

// All local assets required for the app shell to work offline.
//
// MAINTENANCE: when adding a new source file (js/*.js, css/*.css, images/*,
// data/*.json), also list it here so it precaches on install — otherwise a
// user who installs the PWA and then goes offline will see a broken app the
// first time that file is requested. Bump CACHE_VERSION above (fresh Unix
// timestamp) on the same commit so the service worker rebuilds its cache
// instead of serving the stale list. scripts/build.js reminds you about
// CACHE_VERSION but does not touch this list.
const SHELL_ASSETS = [
    './',
    './index.html',
    './css/tokens.css',
    './css/base.css',
    './css/components.css',
    './css/views.css',
    './fonts/InstrumentSans-Variable.ttf',
    './fonts/InstrumentSans-Italic-Variable.ttf',
    './fonts/Lato-Regular.ttf',
    './fonts/Lato-Bold.ttf',
    './fonts/Megan-Display.otf',
    './fonts/Sunday-Regular.ttf',
    './fonts/JosefinSans-SemiBold.woff2',
    './js/app.js',
    './js/password-gate.js',
    './js/i18n.js',
    './js/config.js',
    './js/event-type-filter.js',
    './js/store.js',
    './js/favorites.js',
    './js/festival.js',
    './js/ui.js',
    './js/router.js',
    './js/search.js',
    './js/install.js',
    './js/location.js',
    './js/music.js',
    './js/menu.js',
    './js/notifications.js',
    './js/onboarding.js',
    './js/push.js',
    './js/helpers/geolocation-permission.js',
    './js/helpers/get-stage.js',
    './js/helpers/point-in-polygon.js',
    './js/helpers/prompt-storage.js',
    './js/helpers/safe-storage.js',
    './js/helpers/stage-hysteresis.js',
    './js/views/home.js',
    './js/views/timetable.js',
    './js/views/timetable-grid.js',
    './js/views/info.js',
    './js/views/map.js',
    './js/views/map-common.js',
    './js/views/map-interactive.js',
    './js/views/map-static.js',
    './js/views/map-palette.js',
    './js/views/basemap-layers.js',
    './js/views/user-location.js',
    './js/views/tent.js',
    './js/views/tent-intro.js',
    './js/views/map-layers.js',
    './js/views/map-controls.js',
    './js/views/map-toast.js',
    './js/views/map-flyto.js',
    './js/views/map-search.js',
    './js/helpers/distance.js',
    './js/helpers/festival-pois.js',
    './js/helpers/map-label-translations.js',
    './js/views/favorites.js',
    './manifest.json',
    './vendor/maplibre-gl.js',
    './vendor/maplibre-gl.css',
    './vendor/pmtiles.js',
    './data/basemap.pmtiles',
    // SDF glyph tiles for the map label typography (Megan Display
    // + Lato + Instrument Sans). One .pbf per Unicode range per font,
    // generated by scripts/generate-glyphs.js. Only the Latin-1 range
    // is shipped — covers every character in the festival labels.
    './glyphs/Megan Display/0-255.pbf',
    './glyphs/Megan Display/256-511.pbf',
    './glyphs/Lato Regular/0-255.pbf',
    './glyphs/Lato Regular/256-511.pbf',
    './glyphs/Lato Bold/0-255.pbf',
    './glyphs/Lato Bold/256-511.pbf',
    './glyphs/Instrument Sans Italic/0-255.pbf',
    './glyphs/Instrument Sans Italic/256-511.pbf',
    './glyphs/Instrument Sans/0-255.pbf',
    './glyphs/Instrument Sans/256-511.pbf',
    './icons/icon-192.png',
    './icons/icon-512.png',
    './icons/icon-180.png',
    './images/frame.png',
    './images/datum.png',
    './images/festival-map.webp',
    './images/tent.svg',
    './images/locate.svg',
    './images/fly-navigation.svg',
    './images/compass-rose.svg',
    './images/poi-tent.svg',
    './images/poi-toilet.svg',
    './images/poi-firstaid.svg',
    './images/poi-info.svg',
    './images/poi-generic.svg',
    
    './data/info.json',
    './data/timetable.json',
    './data/map-search-index.json',
    './data/landmarks.geojson',
    './data/regions.geojson',
    './data/gastro.geojson',
    './data/produktion.geojson',
    './data/stages.geojson',
    './data/sterne.geojson',
    './data/food-court.geojson',
    './data/toilets-showers.geojson',
    './data/camping-areas.geojson',
    './data/en/timetable.json',
    './data/_manifest.json'
];

const FONT_URL = 'https://fonts.googleapis.com/css2?family=Lato:wght@400;700;900&family=Space+Grotesk:wght@500;700&display=swap';

// ── Helpers ───────────────────────────────────────────────────────────────

function isSameOrigin(url) {
    return url.origin === self.location.origin;
}

function isLocalAsset(url) {
    // In standalone all requests are relative to the deployment folder.
    // We treat same-origin requests + Google Fonts as app assets.
    return isSameOrigin(url) ||
           url.hostname === 'fonts.googleapis.com' ||
           url.hostname === 'fonts.gstatic.com';
}

function fetchWithTimeout(request, ms = 10000) {
    return fetch(request, {
        cache: 'no-cache',
        signal: AbortSignal.timeout(ms)
    });
}

async function putCache(request, response) {
    if (!response || !response.ok || response.status === 206) return;
    try {
        const cache = await caches.open(CACHE_NAME);
        await cache.put(request, response.clone());
    } catch (err) {
        console.log('[SW] cache put failed', request.url, err.message);
    }
}

// ── Install: shell atomically, then data + fonts best-effort ──────────────

async function precacheShell() {
    const cache = await caches.open(CACHE_NAME);
    await cache.addAll(SHELL_ASSETS);

    try {
        const fontRes = await fetchWithTimeout(FONT_URL, 10000);
        if (fontRes.ok) await cache.put(FONT_URL, fontRes);
    } catch (e) {
        console.log('[SW] Font CSS precache failed', e.message);
    }
}

async function precacheData() {
    const cache = await caches.open(CACHE_NAME);

    let manifest;
    try {
        const res = await fetchWithTimeout('./data/_manifest.json', 10000);
        if (!res.ok) throw new Error('manifest fetch failed');
        manifest = await res.json();
        await cache.put('./data/_manifest.json', res.clone());
    } catch (e) {
        console.log('[SW] Manifest precache failed', e.message);
        return;
    }

    // Discover any additional data files referenced by the manifest pages.
    const dataFiles = new Set(['./data/_manifest.json']);
    (manifest.pages || []).forEach(p => {
        if (!p.slug) return;
        dataFiles.add(`./data/${p.slug}.json`);
        dataFiles.add(`./data/en/${p.slug}.json`);
    });

    const results = await Promise.allSettled(
        Array.from(dataFiles).map(async (url) => {
            try {
                const res = await fetchWithTimeout(url, 10000);
                if (res.ok) {
                    await cache.put(url, res.clone());
                    return { ok: true, url };
                }
                return { ok: false, url, status: res.status };
            } catch (e) {
                return { ok: false, url, error: e.message };
            }
        })
    );

    let cached = 0, failed = 0;
    results.forEach(r => {
        if (r.value?.ok) cached++;
        else {
            failed++;
            console.log('[SW] Failed to precache', r.value?.url || r.reason, r.value?.status || r.reason);
        }
    });
    console.log(`[SW] Precached ${cached}/${dataFiles.size} data files, ${failed} failed`);
}

self.addEventListener('install', e => {
    e.waitUntil(
        precacheShell()
            .then(() => precacheData())
            .then(() => self.skipWaiting())
            .catch(err => {
                console.error('[SW] Install failed', err);
                throw err;
            })
    );
});

// ── Activate: delete old caches, take control ─────────────────────────────

self.addEventListener('activate', e => {
    e.waitUntil(
        caches.keys().then(keys =>
            Promise.all(keys.map(key => {
                if (key !== CACHE_NAME) {
                    console.log('[SW] Deleting old cache', key);
                    return caches.delete(key);
                }
            }))
        ).then(() => self.clients.claim())
    );
});

// ── Fetch strategies ─────────────────────────────────────────────────────

async function cacheFirst(request, fallbackToNetwork = true) {
    const cache = await caches.open(CACHE_NAME);
    // ignoreSearch: the precached shell entries have no query string, but
    // real requests do (?v=... cache-busting, and now start_url's
    // ?page=favorites for the installed-app launch) — without this, an
    // offline launch from the home-screen icon would miss the cache and
    // fail instead of falling back to network.
    const cached = await cache.match(request, { ignoreSearch: true });
    if (cached) return cached;

    if (!fallbackToNetwork) {
        return new Response('Offline asset not cached', { status: 503 });
    }

    try {
        const res = await fetchWithTimeout(request, 10000);
        await putCache(request, res);
        return res.clone();
    } catch (err) {
        return new Response('Network error and asset not cached', { status: 503 });
    }
}

// Notifications and music are both meant to feel current — new lineup
// announcements and alerts are exactly the content where staleness is most
// noticeable. Stale-while-revalidate would show last visit's list first and
// only pick up changes on the visit *after* that. Try the network first
// instead; fall back to cache only when actually offline.
// 12s, not the 6s this started as — cellular round-trips (no wifi, weak
// signal) routinely exceeded a shorter timeout, silently falling back to
// stale cache instead of showing what was actually just published.
async function networkFirst(request, ms = 12000) {
    const cache = await caches.open(CACHE_NAME);
    try {
        const res = await fetchWithTimeout(request, ms);
        if (res.ok) await putCache(request, res.clone());
        return res;
    } catch (err) {
        const cached = await cache.match(request, { ignoreSearch: true });
        return cached || new Response('Offline and not cached', { status: 503 });
    }
}

async function staleWhileRevalidate(request, event) {
    const cache = await caches.open(CACHE_NAME);
    const cached = await cache.match(request);

    const networkPromise = fetchWithTimeout(request, 10000)
        .then(async res => {
            if (res.ok) await putCache(request, res.clone());
            return res;
        })
        .catch(err => {
            console.log('[SW] SWR network failed', request.url, err.message);
            return undefined;
        });

    if (cached) {
        if (event) event.waitUntil(networkPromise);
        return cached;
    }

    const fresh = await networkPromise;
    return fresh || new Response('Offline and not cached', { status: 503 });
}

// Manual "refresh" action (js/store.js's refreshAllData()) — deliberately
// bypasses every strategy above, including their cache-on-failure fallback.
// A user tapping refresh wants to know whether it actually worked; silently
// handing back stale cache on failure (like staleWhileRevalidate/
// networkFirst do for the ambient background case) would look like success
// when it wasn't. Returning a clear failure here lets the client decide to
// keep showing its current in-memory data instead — see refreshAllData()'s
// per-slug try/catch in store.js.
async function networkOnly(request) {
    try {
        const res = await fetchWithTimeout(request, 12000);
        if (res.ok) {
            // Cache under the canonical URL (no ?forceRefresh param), not
            // the request's actual URL — otherwise this lands in a cache
            // entry a later plain reload never looks up (staleWhileRevalidate
            // does an exact cache.match(), no ignoreSearch), so the reload
            // would miss and fall back to whatever was cached before this
            // refresh instead of showing the data it just fetched.
            const canonicalUrl = new URL(request.url);
            canonicalUrl.searchParams.delete('forceRefresh');
            await putCache(new Request(canonicalUrl.toString()), res.clone());
        }
        return res;
    } catch (err) {
        return new Response('Refresh failed — network unavailable', { status: 503 });
    }
}

async function crossOriginAsset(request) {
    const cache = await caches.open(CACHE_NAME);
    const cached = await cache.match(request);
    if (cached) return cached;

    try {
        const res = await fetch(request);
        if (res && (res.type === 'basic' || res.type === 'cors')) {
            await putCache(request, res.clone());
        }
        return res;
    } catch (err) {
        return cached || new Response('Cross-origin asset unavailable offline', { status: 503 });
    }
}

// ── HTTP Range serving from cache (for pmtiles) ────────────────────

// Parse `bytes=A-B` → { start, end } or null. Only the plain single-range
// form is supported; that's all pmtiles.js ever sends. Suffix ranges
// (`bytes=-N`) are technically valid HTTP but pmtiles doesn't emit them,
// so we skip that branch to keep the parser trivial.
//
// KEEP IN SYNC with standalone/server.js's parseRange (the dev server's
// version). The two run in different runtimes so they can't share a
// module directly, but they must agree on what a valid range looks like.
function parseByteRange(header, size) {
    if (!header) return null;
    const m = /^bytes=(\d+)-(\d*)$/.exec(header.trim());
    if (!m) return null;
    const start = Number(m[1]);
    const end = m[2] === '' ? size - 1 : Math.min(Number(m[2]), size - 1);
    if (Number.isNaN(start) || Number.isNaN(end)) return null;
    if (start > end || start >= size) return null;
    return { start, end };
}

// Serve a Range request from the SW cache when the full file is present.
// Returns a 206 Partial Content response with the requested byte slice,
// or null when the resource isn't cached (caller falls back to network).
async function rangeFromCacheOrNetwork(request) {
    const range = request.headers.get('range');
    try {
        const cache = await caches.open(CACHE_NAME);
        // Match against the URL only — our precache stores a full-file
        // Response keyed by the plain request; a range-header'd Request
        // would fail to match unless we normalise.
        const cached = await cache.match(new Request(request.url));
        if (cached) {
            const fullBuffer = await cached.arrayBuffer();
            const parsed = parseByteRange(range, fullBuffer.byteLength);
            if (!parsed) {
                return new Response(null, {
                    status: 416,
                    headers: {
                        'Content-Range': `bytes */${fullBuffer.byteLength}`,
                    },
                });
            }
            const slice = fullBuffer.slice(parsed.start, parsed.end + 1);
            return new Response(slice, {
                status: 206,
                statusText: 'Partial Content',
                headers: {
                    'Content-Type':
                        cached.headers.get('Content-Type') ||
                        'application/octet-stream',
                    'Content-Range':
                        `bytes ${parsed.start}-${parsed.end}/${fullBuffer.byteLength}`,
                    'Content-Length': String(slice.byteLength),
                    'Accept-Ranges': 'bytes',
                    'Cache-Control': 'public, max-age=31536000, immutable',
                },
            });
        }
    } catch (err) {
        // Not all thrown values are Error instances — DOMExceptions and
        // spec-thrown strings both surface here. `err?.message ?? err`
        // keeps the log meaningful in either case.
        console.log('[SW] range from cache failed', err?.message ?? err);
    }
    // Cache miss or error → hand to the network. If we're offline this
    // rejects; a 503 keeps pmtiles's promise chain from swallowing the
    // error silently.
    try {
        return await fetch(request);
    } catch (err) {
        // Log at warn level so a regression in range-serving doesn't
        // stay invisible — the 503 response itself is intentional UX
        // for a genuinely-offline user, but a 503 in an online session
        // is a bug we want to see.
        console.warn('[SW] range network fallback failed → 503', err?.message ?? err);
        return new Response('Range not available offline', { status: 503 });
    }
}

self.addEventListener('fetch', e => {
    const { request } = e;
    if (request.method !== 'GET') return;

    // Range requests need special handling. Two cases:
    //  • The resource IS precached (e.g. basemap.pmtiles): slice bytes
    //    out of the cached full-file response and return a synthetic 206.
    //    Without this, offline pmtiles reads fail; the network layer
    //    can't reach the server, and cache-first would hand back a full
    //    200 which pmtiles rejects with "content-length exceeding request".
    //  • The resource ISN'T precached: pass through to the network so
    //    the origin server can serve a real 206 (dev server does this;
    //    prod hosts almost always do).
    if (request.headers.has('range')) {
        const url = new URL(request.url);
        if (isLocalAsset(url)) {
            e.respondWith(rangeFromCacheOrNetwork(request));
        }
        return;
    }

    const url = new URL(request.url);

    // Local app assets + Google Fonts
    if (isLocalAsset(url)) {
        if (url.pathname.includes('/data/') && url.searchParams.has('forceRefresh')) {
            e.respondWith(networkOnly(request));
        } else if (url.pathname.endsWith('notifications.json') || url.pathname.endsWith('music.json') || url.pathname.endsWith('timetable.json')) {
            e.respondWith(networkFirst(request));
        } else if (url.pathname.includes('/data/')) {
            e.respondWith(staleWhileRevalidate(request, e));
        } else {
            e.respondWith(cacheFirst(request));
        }
        return;
    }

    // Cross-origin assets referenced by content (images, CSS, fonts).
    e.respondWith(crossOriginAsset(request));
});

// ── Push notifications ──────────────────────────────────────────────────────
//
// Payload shape is set server-side by class-push.php's send_to_all():
// {title, body, url}. url is optional (defaults to the app root below);
// class-notifications.php doesn't currently set one, but the shape leaves
// room for a future deep link (e.g. straight to the News tab).

self.addEventListener('push', e => {
    let payload = { title: 'Bucht der Träumer', body: '' };
    try {
        if (e.data) payload = { ...payload, ...e.data.json() };
    } catch (err) {
        console.log('[SW] Push payload parse failed', err.message);
    }

    e.waitUntil(
        self.registration.showNotification(payload.title, {
            body: payload.body,
            icon: './icons/icon-192.png',
            badge: './icons/icon-192.png',
            data: { url: payload.url || './' },
        })
    );
});

self.addEventListener('notificationclick', e => {
    e.notification.close();
    const targetUrl = e.notification.data?.url || './';

    e.waitUntil(
        self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then(clientList => {
            // Prefer focusing an already-open tab over stacking a new one —
            // most opens will be someone re-opening the installed app they
            // already have running/backgrounded. That tab is already on
            // whatever page it was on, though, so it needs telling where to
            // go (app.js's message listener reads targetUrl's ?notif= param
            // and routes there) — openWindow's fresh document load reads
            // the same param straight off location.search instead, no
            // message needed.
            for (const client of clientList) {
                if (client.url.includes(self.registration.scope) && 'focus' in client) {
                    client.postMessage({ type: 'notification-click', url: targetUrl });
                    return client.focus();
                }
            }
            return self.clients.openWindow(targetUrl);
        })
    );
});

// ── Message handling ──────────────────────────────────────────────────────

self.addEventListener('message', e => {
    if (!e.data) return;
    if (e.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});
