import { t } from '../i18n.js';

// ─── Data + palette ────────────────────────────────────────────────────
//
// Palette lifted from the illustrated bucht.png. Keeping it here (not in
// tokens.css) because these tones are map-specific styling for MapLibre's
// paint expressions, not app-wide theme colours.

const PNG_MAGENTA_DEEP = '#8b235f';
const PNG_MAGENTA_LINE = '#c22a4c';
const PNG_MAGENTA_HALO = '#3b0f26';
const PNG_STAGE_FILL_WEST = '#7d1b2b';
const PNG_STAGE_FILL_EAST = '#c22a4c';
const PNG_FOOD_GREEN = '#6ACE45';
const PNG_FOOD_LINE = '#3f7a26';
const PNG_FOOD_HALO = '#1a3d10';
const PNG_INFO_RED = '#c93535';
const PNG_INFO_LINE = '#7a1c1c';
const PNG_CREAM = '#f2e9dc';
const PNG_STAGE_LINE = '#e94a8c';
const PNG_SHORE_LINE = '#f2e9dc';
// Additional palette used only by the pmtiles basemap style:
//   LAND_DEEP  the deep dry-land magenta that dominates the PNG's west
//   LAND_MID   a slightly lighter mid-magenta "earth" fill on top of it
//   WATER      dark navy blue for lakes/rivers, matching Helenesee's tone
const PNG_LAND_DEEP = '#5c1c47';
const PNG_LAND_MID = '#8b235f';
const PNG_WATER = '#1e2a4a';

// MapTiler key retained only in case we want to fall back to their
// glyph server; the vendored SDF glyphs under standalone/glyphs/ are the
// primary source now. Left as an unused const for later reference.
const MAPTILER_KEY = '06rHa9F6cOokrirDiPlF'; // eslint-disable-line no-unused-vars

// Font stacks for map labels. These names match the folder names under
// standalone/glyphs/ (generated by scripts/generate-glyphs.js from the
// TTF/OTF files in standalone/fonts/). The array is passed to MapLibre's
// `text-font` layout property.
//
// We keep the array single-font on purpose: MapLibre requests the
// concatenated fontstack ("A,B/{range}.pbf") for multi-font stacks, and
// we'd have to composite each combination with `fontnik.composite`. Our
// Latin-1 glyph ranges already cover every character our labels use
// (ASCII + ÄÖÜßäöü), so the fallback isn't needed.
const FONT_DISPLAY = ['Megan Display'];
const FONT_HELPER = ['Instrument Sans Italic'];

// Slug list used to two-tone the stage polygons: west-shore stages take
// the deeper burgundy fill (matches the ATLANTIS/PORTO LOCO area on the
// PNG), everything else takes the brighter pink of the east crescent.
const WEST_STAGES = [
    'waldtraut',
    'unterholz',
    'sektamt',
    'schlupfloch',
    'porto-loco',
    'stroboklo',
    'atlantis',
    'neustockland',
];

// Combined bbox of the 16 real stage polygons. Used at load to fit the
// initial view to every stage the user might want to look at, with a bit
// of padding for the page header and rotation slack. Recomputing this
// live from the geojson works too but adds a source-loaded await that
// visibly "jumps" the map — hard-coded values keep the first frame
// already on-target.
//   stages lng: 14.4826..14.5032, lat: 52.2713..52.2765
const STAGES_BBOX = [
    [14.4820, 52.2708], // SW
    [14.5038, 52.2770], // NE
];

// ─── View ──────────────────────────────────────────────────────────────

export function renderMap(container) {
    container.innerHTML = `
        <div class="festival-map" id="festivalMap"></div>
    `;

    const stage = container.querySelector('#festivalMap');

    // Same dynamic-sizing trick as the PNG map: the sub-page header height
    // varies with viewport, so we measure top-offset at mount and fill the
    // remaining viewport, refreshing on resize (but skipping during a
    // MapLibre gesture to avoid mid-pinch relayouts).
    const gestureState = { active: false };
    const sizeStage = () => {
        if (gestureState.active) return;
        const top = stage.getBoundingClientRect().top;
        const h = Math.max(200, window.innerHeight - top);
        stage.style.height = `${h}px`;
    };
    sizeStage();
    const onResize = () => sizeStage();

    if (window.__festivalMapCleanup) window.__festivalMapCleanup();
    window.addEventListener('resize', onResize);
    window.addEventListener('orientationchange', onResize);

    // Defer map init until layout has settled — MapLibre reads container
    // width/height in its constructor and stashes them, so building it
    // before we've set the height would leave it thinking the canvas is
    // 0×0 until the next resize. `requestAnimationFrame` gives the browser
    // a paint to apply our style.height above.
    let map;
    requestAnimationFrame(() => {
        map = createMap(stage, gestureState);
    });

    window.__festivalMapCleanup = () => {
        window.removeEventListener('resize', onResize);
        window.removeEventListener('orientationchange', onResize);
        // MapLibre .remove() releases the GL context, workers, and every
        // registered event listener — essential when the router navigates
        // away, otherwise a WebGL context leaks per visit.
        if (map) map.remove();
    };
}

function createMap(stage, gestureState) {
    const maplibregl = window.maplibregl;
    if (!maplibregl) {
        stage.innerHTML =
            `<div class="festival-map-error">${t('common.noContent')}</div>`;
        return null;
    }

    // Register the pmtiles:// protocol so MapLibre can read our
    // precached Protomaps slice. addProtocol is a global registration —
    // if this view is remounted the second call overwrites with the same
    // handler, which is a no-op.
    if (window.pmtiles) {
        const protocol = new window.pmtiles.Protocol();
        maplibregl.addProtocol('pmtiles', protocol.tile);
    }

    const map = new maplibregl.Map({
        container: stage,
        style: buildStyle(),
        // Initial bounds cover every stage polygon plus some padding. The
        // rotation (bearing) is baked into `bounds` at construction time
        // so the very first frame already shows the whole festival strip.
        bounds: STAGES_BBOX,
        fitBoundsOptions: {
            // Pin the bearing INSIDE fit options so MapLibre computes the
            // fit WITH the rotation baked in. Without this, fitBounds sets
            // up the camera at bearing 0 first and only rotates afterwards,
            // which on a landscape viewport lands on a wider zoom than we
            // want and defeats the whole point of the portrait rotation.
            bearing: -90,
            padding: { top: 60, right: 30, bottom: 30, left: 30 },
        },
        minZoom: 13,
        maxZoom: 19,
        bearing: -90,
        pitch: 0,
        attributionControl: { compact: false },
    });

    // Zoom-in/-out buttons and rotate-reset intentionally omitted — the
    // whole interaction is pinch / drag on touch. Attribution stays
    // (required by MapTiler + OSM).

    // Wire up gesture tracking so the resize handler above knows when to
    // skip. `touchstart` and `pointerdown` both trigger; either works.
    stage.addEventListener('pointerdown', () => { gestureState.active = true; });
    stage.addEventListener('pointerup', () => { gestureState.active = false; });
    stage.addEventListener('pointercancel', () => { gestureState.active = false; });

    map.on('load', () => addOverlayLayers(map));
    map.on('error', (e) => {
        // Surface style / source errors to the console so a broken
        // pmtiles fetch or missing tile URL doesn't fail silently. In
        // prod this stays quiet unless something actually breaks.
        // eslint-disable-next-line no-console
        console.error('[festival-map] MapLibre error', e && (e.error || e));
    });
    return map;
}

// Tier A illustrated basemap: Protomaps vector data (data/basemap.pmtiles)
// painted in the PNG's palette — land tinted magenta, water dark navy,
// no roads, no POIs, no labels. Everything the user actually wants
// (stages, venues, food) sits on top via addOverlayLayers().
//
// Layer names come from Protomaps' schema:
// https://docs.protomaps.com/basemaps/layers  (earth, water, roads,
// places, pois, landcover, landuse, boundaries, buildings). Tier A uses
// only earth + water.
function buildStyle() {
    return {
        version: 8,
        glyphs: 'glyphs/{fontstack}/{range}.pbf',
        sources: {
            basemap: {
                type: 'vector',
                url: 'pmtiles://data/basemap.pmtiles',
                attribution:
                    '\u00a9 <a href="https://openstreetmap.org" target="_blank">OpenStreetMap</a> \u00b7 <a href="https://protomaps.com" target="_blank">Protomaps</a>',
            },
        },
        layers: [
            // Solid dark-magenta "canvas" behind everything. Also fills
            // the tiny strip outside the pmtiles bbox during panning.
            {
                id: 'background',
                type: 'background',
                paint: { 'background-color': PNG_LAND_DEEP },
            },
            // Land polygon from Protomaps' `earth` source-layer. 0.85
            // opacity lets the darker background bleed through slightly
            // for a bit of tonal variation.
            {
                id: 'earth',
                source: 'basemap',
                'source-layer': 'earth',
                type: 'fill',
                paint: {
                    'fill-color': PNG_LAND_MID,
                    'fill-opacity': 0.85,
                },
            },
            // Water polygons — lakes, rivers, ocean. Dark navy blue
            // mimics the PNG's Helenesee.
            {
                id: 'water',
                source: 'basemap',
                'source-layer': 'water',
                type: 'fill',
                paint: {
                    'fill-color': PNG_WATER,
                    'fill-opacity': 1.0,
                },
            },
        ],
    };
}

// ─── Overlay layers (geojsons on top of the basemap) ─────────────────

function addOverlayLayers(map) {
    // Helenesee north shore — the OSM Helenesee polygon clipped to the
    // festival bbox on the north half (see standalone/data/helenesee-shore.geojson).
    map.addSource('shore-src', {
        type: 'geojson',
        data: 'data/helenesee-shore.geojson',
    });
    map.addLayer({
        id: 'shore',
        source: 'shore-src',
        type: 'line',
        layout: { 'line-cap': 'round', 'line-join': 'round' },
        paint: {
            'line-color': PNG_SHORE_LINE,
            'line-width': [
                'interpolate', ['linear'], ['zoom'],
                12, 0.8,
                14, 1.6,
                16, 2.6,
                18, 4,
            ],
            'line-opacity': 0.9,
            'line-blur': 0.4,
        },
    });

    // Stages (16 real polygons from the real-floor-geo-data PR). The
    // fill switches on slug so west-cluster stages read as burgundy
    // (matches the PNG's west shore) and east stages as brighter pink.
    map.addSource('stages-src', {
        type: 'geojson',
        data: 'data/stages.geojson',
    });
    map.addLayer({
        id: 'stages',
        source: 'stages-src',
        type: 'fill',
        paint: {
            'fill-color': [
                'match', ['get', 'slug'],
                WEST_STAGES, PNG_STAGE_FILL_WEST,
                PNG_STAGE_FILL_EAST,
            ],
            'fill-opacity': 0.55,
        },
    });
    map.addLayer({
        id: 'stages-outline',
        source: 'stages-src',
        type: 'line',
        paint: {
            'line-color': PNG_STAGE_LINE,
            'line-width': 1.6,
            'line-opacity': 0.95,
        },
    });
    map.addLayer({
        id: 'stages-label',
        source: 'stages-src',
        type: 'symbol',
        layout: {
            'text-field': [
                'upcase',
                ['coalesce', ['get', 'slug'], ['get', 'name'], ''],
            ],
            'text-font': FONT_DISPLAY,
            'text-size': [
                'interpolate', ['linear'], ['zoom'],
                13, 11,
                15, 15,
                17, 22,
            ],
            'text-letter-spacing': 0.15,
            'text-anchor': 'center',
            'text-max-width': 8,
            'text-allow-overlap': false,
            'text-optional': true,
            'text-padding': 4,
            'text-rotation-alignment': 'viewport',
            'text-pitch-alignment': 'viewport',
        },
        paint: {
            'text-color': PNG_CREAM,
            'text-halo-color': PNG_MAGENTA_HALO,
            'text-halo-width': 2,
            'text-halo-blur': 0.4,
        },
    });

    // Art venues — 22 polygons from Lageplan (1)+(2) merged by felt:id.
    map.addSource('venues-src', {
        type: 'geojson',
        data: 'data/venues.geojson',
    });
    map.addLayer({
        id: 'venues',
        source: 'venues-src',
        type: 'fill',
        paint: {
            'fill-color': PNG_MAGENTA_DEEP,
            'fill-opacity': 0.42,
        },
    });
    map.addLayer({
        id: 'venues-outline',
        source: 'venues-src',
        type: 'line',
        paint: {
            'line-color': PNG_MAGENTA_LINE,
            'line-width': 1.1,
            'line-opacity': 0.9,
        },
    });
    map.addLayer({
        id: 'venues-label',
        source: 'venues-src',
        type: 'symbol',
        minzoom: 14,
        layout: {
            'text-field': ['get', 'name'],
            'text-font': FONT_HELPER,
            'text-size': [
                'interpolate', ['linear'], ['zoom'],
                14, 9,
                16, 11,
                17, 13,
            ],
            'text-anchor': 'center',
            'text-max-width': 7,
            'text-allow-overlap': false,
            'text-optional': true,
            'text-padding': 2,
            'text-rotation-alignment': 'viewport',
            'text-pitch-alignment': 'viewport',
        },
        paint: {
            'text-color': PNG_CREAM,
            'text-halo-color': PNG_MAGENTA_HALO,
            'text-halo-width': 1.4,
        },
    });

    // Food stalls + red Community Corner info point (L3, 21 polygons).
    // Category is baked in during data prep so we can drive fill and halo
    // off a single `category` property.
    map.addSource('foodstalls-src', {
        type: 'geojson',
        data: 'data/food.geojson',
    });
    map.addLayer({
        id: 'foodstalls',
        source: 'foodstalls-src',
        type: 'fill',
        paint: {
            'fill-color': [
                'match', ['get', 'category'],
                'info', PNG_INFO_RED,
                PNG_FOOD_GREEN,
            ],
            'fill-opacity': 0.55,
        },
    });
    map.addLayer({
        id: 'foodstalls-outline',
        source: 'foodstalls-src',
        type: 'line',
        paint: {
            'line-color': [
                'match', ['get', 'category'],
                'info', PNG_INFO_LINE,
                PNG_FOOD_LINE,
            ],
            'line-width': 1.1,
            'line-opacity': 0.9,
        },
    });
    map.addLayer({
        id: 'foodstalls-label',
        source: 'foodstalls-src',
        type: 'symbol',
        minzoom: 15,
        layout: {
            'text-field': ['get', 'name'],
            'text-font': FONT_HELPER,
            'text-size': [
                'interpolate', ['linear'], ['zoom'],
                15, 9,
                17, 12,
            ],
            'text-anchor': 'center',
            'text-max-width': 7,
            'text-allow-overlap': false,
            'text-optional': true,
            'text-padding': 2,
            'text-rotation-alignment': 'viewport',
            'text-pitch-alignment': 'viewport',
        },
        paint: {
            'text-color': PNG_CREAM,
            'text-halo-color': [
                'match', ['get', 'category'],
                'info', PNG_INFO_LINE,
                PNG_FOOD_HALO,
            ],
            'text-halo-width': 1.4,
        },
    });

    // Popup on click for any interactive feature. Uses the same cream
    // popup styling as the fusion-map POC, defined in views.css.
    map.on('click', (e) => {
        const features = map.queryRenderedFeatures(e.point, {
            layers: ['venues', 'foodstalls', 'stages'],
        });
        if (!features.length) return;
        const f = features[0];
        const p = f.properties || {};
        const name = p.name || p.slug || '';
        const desc = p.description || '';
        const cat = p.category || p.slug || '';
        new window.maplibregl.Popup({ closeButton: true, offset: 8 })
            .setLngLat(e.lngLat)
            .setHTML(`
                <div class="festival-map-popup">
                    <div class="festival-map-popup-title">${escapeHtml(name)}</div>
                    ${cat ? `<div class="festival-map-popup-cat">${escapeHtml(String(cat))}</div>` : ''}
                    ${desc ? `<div class="festival-map-popup-desc">${escapeHtml(desc)}</div>` : ''}
                </div>
            `)
            .addTo(map);
    });

    ['venues', 'foodstalls', 'stages'].forEach((id) => {
        map.on('mouseenter', id, () => { map.getCanvas().style.cursor = 'pointer'; });
        map.on('mouseleave', id, () => { map.getCanvas().style.cursor = ''; });
    });
}

function escapeHtml(s) {
    return String(s).replace(/[&<>"']/g, (c) => (
        { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]
    ));
}
